version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: csapp
      MYSQL_ROOT_USER: root
      # MYSQL_PASSWORD: root
    ports:
      - "3307:3306" # т.к. на моей windows машине работает служба mysql на порту 3306
    volumes:
      - mysql_data:/var/lib/mysql

  app:
    image: csapp
    container_name: spring_csapp
    restart: always
    ports:
      - "8080:8080"  # маппинг портов
    volumes:
      - excel_data:/var/lib/excel_data
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/csapp?allowPublicKeyRetrieval=true&useSSL=false
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      EXCEL_FILE_PATH: /var/lib/excel_data
    depends_on:
      - mysql  # Обеспечивает запуск MySQL перед приложением

volumes:
  mysql_data:
  excel_data: