# spring раздел включает в себя настройки, связанные с Spring Framework и его модулями.
spring:
  # данныйе для подключения к базе
  datasource:
    url: jdbc:mysql://localhost:3306/csapp?allowPublicKeyRetrieval=true&useSSL=false
    username: develop
    password: develop

  mvc:
    # Настройки, связанные с маршрутизацией запросов в Spring MVC
    pathmatch:
      # Устанавливает стратегию для сопоставления URL-путей с помощью Ant-масок. Ant-маски позволяют использовать такие шаблоны,
      # как `/**` для сопоставления всех путей или `/users/*` для сопоставления всех путей, начинающихся с `/users/`
      matching-strategy: ANT_PATH_MATCHER


  # The SQL dialect makes Hibernate generate better SQL for the chosen database
  jpa:
    # Дополнительные свойства для настройки JPA и Hibernate
    properties:
      hibernate:
        # Определяет диалект SQL, используемый Hibernate для генерации оптимального SQL-кода для конкретной базы данных (в данном случае для MySQL с использованием InnoDB).
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect

#JPA Settings
  # `ddl_auto`: Управляет автоматическим созданием и изменением схемы базы данных при запуске приложения.
  # `update`: Hibernate обновляет схему базы данных для соответствия изменениям в сущностях без удаления данных.
  jpa.hibernate.ddl_auto: update